services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: ncadm_api_prod
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:3100:3100"
    networks:
      - back_db_network
      - network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        APP_BASE_PATH: ${APP_BASE_PATH:-}
        VITE_API_URL: ${VITE_API_URL:-}
    container_name: ncadm_web_prod
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - network
    depends_on:
      - api
    restart: unless-stopped

networks:
  network:
    driver: bridge
  back_db_network:
    external: true
